### ISSUE TITLE
Run SACRED tutorial

### ISSUE THREAD

**Issue by vcheplygina** [vcheplygina/cats-scans#2]

**Comment by irmavdbrandt** [comment]
The tutorial does not include setting up a MongoDB (used in the Sacredboard), so this has to be done first.

**Comment by irmavdbrandt** [comment]
Note: running Sacred in PyCharm will not work, so running scripts and experimenting with Sacred has to be done via the terminal (python <namefile>.py)

**Comment by irmavdbrandt** [comment]
Note: it is easier to access the Omniboard from Sacred instead of the Sacredboard. Next to the tutorial of this issue I used this other tutorial: https://towardsdatascience.com/improve-your-workflow-by-managing-your-machine-learning-experiments-using-sacred-d51dd2b0047e
