### ISSUE TITLE
Write instructions about sharing data/networks 

### ISSUE THREAD

**Issue by vcheplygina** [vcheplygina/cats-scans#4]

**Comment by vcheplygina** [comment]
Let's try to use OSF (see README.MD), in this project: https://osf.io/x2fpg/  Please create accounts and send me your usernames so I can invite you.

**Comment by irmavdbrandt** [comment]
(I think) my username is: Irma Van den Brandt. I cannot find any other name on my profile.

**Comment by vcheplygina** [comment]
Yes, just searching by name works!
