### ISSUE TITLE
Embedding error:

### ISSUE THREAD

**Issue by MagicHealer** [vcheplygina/cats-scans#55]
Hi! I am trying to used task2vec to embed tasks. Can anyone guide me? I always encounter errors.

For embedding error:
Traceback (most recent call last):
  File "/home/admin1/CSD/ALaM/Jonel/task2vec_fullcode/SampleEmbedding", line 10, in <module>
    dataset = get_dataset(root='cifar10')
  File "/home/admin1/CSD/ALaM/Jonel/task2vec_fullcode/datasets.py", line 450, in get_dataset
    return _DATASETS[config.name](os.path.expanduser(root), config, rand_int)
AttributeError: 'str' object has no attribute 'name'

Traceback (most recent call last):
  File "/home/admin1/CSD/ALaM/Jonel/aws-cv-task2vec/main.py", line 51, in <module>
    dataset = get_dataset('cifar10')
  File "/home/admin1/CSD/ALaM/Jonel/aws-cv-task2vec/datasets.py", line 362, in get_dataset
    print(_DATASETS[config.name])
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by vcheplygina** [comment]
As far as I know we adapted the task2vec code and did not work with the CIFAR dataset. The SampleEmbedding code is there, because it is a copy from the original task2vec repository https://github.com/awslabs/aws-cv-task2vec , which they probably updated since then. Try their most recent version / tutorial?

**Comment by MagicHealer** [comment]
@vcheplygina May I also ask how can I add dataset in data_import.py you have provided? I want to add other dataset like ImageNet or CUB dataset. Thank you.

**Comment by MagicHealer** [comment]
Do you also have the passeriformes.txt and taxonomy.txt for CUB dataset? Thank you

**Comment by vcheplygina** [comment]
Hi, we cannot help you with datasets we did not create outselves, please ask to the dataset creators.
